# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Config file for Label Bot
# Disable label by Drift product
product: false
language:
  # Disable issue labeling (not accurate)
  issue: false
  # Enable pr labeling
  pullrequest: true
  labelprefix: 'lang: '
  # To re-map extension to languages
  extensions:
    terraform: ['tf']
    typescript: ['ts']
  # To map languages based on project directory structure:
  paths:
    src:
      frontend: 'go'
      cartservice: 'c#'
      productcatalogservice: 'go'
      currencyservice: 'javascript'
      paymentservice: 'javascript'
      shippingservice: 'go'
      emailservice: 'python'
      checkoutservice: 'go'
      recommendationservice: 'python'
      adservice: 'java'
      loadgenerator: 'python'
    terraform:
      # To designate the default language for a subdirectory use '.'
      .: 'terraform'
    tests:
      .: 'python'
      # More specific path designations will overwrite the default
      cartservice: 'c#'
      ratingservice: 'python'
    website:
      .: 'javascript'
      images: 'svg'
