version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_PORT: "6379"
      REDIS_ADDR: "redis:${REDIS_PORT}"
      LISTEN_ADDR: "localhost"
      PORT: "7070"
    volumes:
        - /app/obj/
        - /app/bin/
        - /app/out/
  redis:
    image: "redis:alpine"