version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_PORT: "6379"
      REDIS_ADDR: "redis:6379"
      LISTEN_ADDR: "localhost"
      PORT: "7070"
  redis:
    image: "redis:alpine"